sudo: required
services:
    - docker
    
before_install:
    - docker build -t thewannabesavant/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run thewannabesavant/react-test npm test -- --coverage
    
after_success:
    - docker build -t thewannabesavant/multi-client ./client
    - docker build -t thewannabesavant/multi-nginx ./nginx
    - docker build -t thewannabesavant/multi-server ./server
    - docker build -t thewannabesavant/multi-worker ./worker
    #Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push images to docker hub
    - docker push thewannabesavant/multi-client
    - docker push thewannabesavant/multi-nginx
    - docker push thewannabesavant/multi-server
    - docker push thewannabesavant/multi-worker